app/components/sessions/SessionsController.js, app/components/speakers/SpeakersController.js, app/components/tracks/TracksController.js
=> check null before undefined

app/libs/angular-storage.js
=> add license and versoin info to ngStorage

app.js, app/components/map/MapController.js, app/components/map/map.html, app/components/sidenav/sidenav.html, app/components/sponsors/SponsorsController.js, app/components/sponsors/sponsors.html, app/components/tracks/TracksController.js, index.html, testapi/event/3/sponsors
@creativepsyco please review and merge :)
=> add sponsor view

app/components/speakers/SpeakersController.js, app/components/speakers/speakerdialog.html, app/components/speakers/speakers.html
=> add dialog popouts for speakers

app/components/sessions/sessions.html, app/components/speakers/speakers.html
=> add search filters in sessions and speakers

app/components/speakers/speakerdialog.html
=> add more details in the speaker dialogs

app/components/common/ApiJsonFactory.js, config.js
=> factor for an extra /event url suffix in testapi

app/components/map/MapController.js, app/components/sessions/SessionsController.js, app/components/speakers/SpeakersController.js, app/components/sponsors/SponsorsController.js, app/components/tracks/TracksController.js, config.js
=> reduce an extra $storage variable from the controllers

.gitignore, README.md, gulpfile.js, package.json
=> add gulp deployment config

app.js, app/components/map/MapController.js, app/components/sessions/SessionsController.js, app/components/sidenav/sidenav.html, app/components/speakers/SpeakersController.js, app/components/sponsors/SponsorsController.js, app/components/tracks/TracksController.js
state names should not start with /
this was not allowing me to create state
based modal dialogs
=> fix names of ui-router states

app.js, app/components/sidenav/sidenav.html, app/components/twitterwall/TwitterwallController.js, app/components/twitterwall/twitterwall.html, assets/js/twitter-widget.js, index.html
=> add twitterwall section

app.js, app/components/common/ApiJsonFactory.js, app/components/sessions/SessionsController.js
=> fix some issues with fetching sessions

app/components/sessions/SessionsController.js, app/components/speakers/SpeakersController.js, assets/js/Utils.js
speakers - > alphabetical
sessions -> begin time
=> Sorting of speakers and sessions

app/components/sidenav/sidenav.html, assets/img/ic_toolbar_back.svg
=> add back button to close sidebar

app.js, config.js, package.json
=> allow setting theme colors in config.js

app/components/sessions/sessiondialog.html, app/components/sessions/sessions.html
=> show speakers under sessions

app/components/sessions/sessions.html, app/components/tracks/TracksController.js, app/components/tracks/trackdialog.html, app/components/tracks/tracks.html, bower.json, gulpfile.js, index.html, testapi/event/1/sessions, testapi/event/1/sponsors
Tracks are made clickable. On clicking a track, a new dialog box opens which shows all the sessions listed in that track. Solves the issue #55
=> track dialog box added, sessions of respective track shown

app/components/sessions/SessionsController.js, app/components/speakers/SpeakersController.js, app/components/speakers/speakerdialog.html
The speaker dialog box shows the sessions addressed by the speaker in card layout. Clicking on this sessions opens the dialog module for the particular session
=> Speaker dialog module shows sessions addressed by the speaker

app/components/sessions/sessiondialog.html, app/components/speakers/speakerdialog.html, app/components/tracks/trackdialog.html
Titles no longer display when they are empty.
=> Fixed extra margins

app/components/speakers/speakerdialog.html, app/components/sponsors/sponsors.html, assets/scss/main.scss, assets/scss/settings/colors.scss, assets/scss/settings/fonts.scss, config.scss, index.html
Organisers may now choose a unified color theme for their event application in the config.scss file.
=> Unified Colors

index.html
=> gulp: cleaned the js/css because gulp does it automatically

app/components/speakers/speakers.html, assets/css/main.css, assets/scss/main.scss
When we are moving the mouse over the speakers view all list, we don't get the clickable feeling.
So added the cursor pointer to the speakers list.
=> Added pointer style to speakers view all.

app/components/speakers/SpeakersController.js
=> fix speaker position field name

app/components/speakers/SpeakersController.js
=> fix for undefined as well as null check

app/components/sessions/sessions.html, app/components/speakers/speakers.html
=> increase performance : use track by

app/components/twitterwall/singletweet.js, index.html
Source for the solution : https://docs.angularjs.org/error/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20tweetDirective
=> #146 Injector error solved

app/components/twitterwall/twitterwall.html
Now , it will work for both modes.
=> #146 Path of image fixed

src/appComponents/speakers/speakers.html
@championswimmer 
replica of #131 and resolves #132. just improved the `speaker.html` sections' side-bar.
since tracks view has been changed so need to first make it like before.so will be working on that.
=> consistency in side-bar

src/appComponents/common/ApiJsonFactory.js, src/appComponents/speakers/SpeakersController.js, src/appComponents/twitterwall/background-directive.js, src/appComponents/twitterwall/singletweet.js
@juslee ,@championswimmer , this is in regard of [this](https://www.codacy.com/app/triplez/open-event-webapp/issues?bid=3233857&step=20&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiRXJyb3IgUHJvbmUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbbnVsbF19XQ%3D%3D)
=> codacy issues set1

.jshintrc
As discussed with regard to issue #176 .
=> #176 jshint angular synchronised

.travis.yml, karma.conf.js
Followed this http://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647 .
@juslee , Hope it will work .
=> Travis with Karma

index.html, src/appComponents/speakers/SpeakersController.js, src/appComponents/speakers/Speakersdirective.js, src/appComponents/speakers/speakerdirective.html, src/appComponents/speakers/speakers.html, src/assets/css/theme1.css
@juslee , @championswimmer  
**LIVE VERSION** http://peddler-maurice-60217.bitballoon.com/#/speakers
Its ready to merge .
=> Speaker View

package.json, src/generator/.eslintrc, src/generator/app.js, src/generator/backend/generator.js, src/generator/backend/schedule.tpl
check this PR out,
locally run
```
npm install
npm run server.generator
```
Visit localhost:3000 -> you'll see the form for generator
Visit localhost:3000/generate -> you'll see OTS16 data schedule page
=> create basic express app that runs the generator

.eslintrc, .hound.yml
@championswimmer @juslee , It will solve es6 config issues 
Added .hound.yml
Added .eslintrc
=> config files added

src/generator/backend/assets/_scss/.gitignore, src/generator/backend/assets/_scss/_base/_config.scss, src/generator/backend/assets/_scss/_themes/_dark-theme/_dark.scss, src/generator/backend/assets/_scss/_themes/_light-theme/_light.scss, src/generator/backend/assets/_scss/application.scss
@mariobehling  , @juslee  ,@championswimmer
**How to run this ?**
For now , till the process automates  which will be handled at backend after a parameter light or dark is passed in POST request .
1. Install Ruby 
2. Install SASS
3. Run sass --watch /path/application.scss:/path/schedule.css
This will create schedule.css inside the path you have given .This will be the default CSS that is same as the current CSS .
4. For creating light theme , go to _themes/_light-theme and run sass --watch _light.scss:schedule.css
This will create a schedule.css with background color light gray .
5. For creating light theme , go to _themes/_dark-theme and run sass --watch _dark.scss:schedule.css
This will create a schedule.css with background color  gray .
I will optimize _application.scss in next PR , …
=> sass files with light and dark theme

LICENSE.md, README.md
=> add README and LICENSE

dist/.gitignore, src/generator/backend/schedule.tpl
Solves this issue
https://github.com/fossasia/open-event-webapp/issues/294 
=> fix css includes for heroku

src/generator/backend/_scss/application.scss, src/generator/backend/tracks.tpl
@juslee, @championswimmer 
Related issue https://github.com/fossasia/open-event-webapp/issues/286
View 1
View 2 
Improvements
=> Pop-over UI/UX improvements

src/generator/backend/_scss/application.scss, src/generator/backend/generator.js, src/generator/backend/schedule.tpl, src/generator/backend/tracks.tpl
View 1 : **Tracks button** 
View 2 : **How it looks choosing a light theme **
=> Track Anchor in schedule.tpl 

src/generator/www/index.html, src/generator/www/js/form.js
solves this issue https://github.com/fossasia/open-event-webapp/issues/305
=> radio group to select one among different data sources

src/generator/app.js, src/generator/backend/dist.js, src/generator/backend/generator.js, src/generator/www/index.html, src/generator/www/js/form.js
To address this issue 
https://github.com/fossasia/open-event-webapp/issues/305
=> Handle different data source options in generator

dist/.gitignore, src/generator/backend/_scss/application.scss, src/generator/backend/generator.js, src/generator/backend/tracks.tpl
ISSUE #301
@championswimmer  @mariobehling  @juslee , Please check the responsivity and report any bugs if you face. I have tried my best to cover standard breakpoints.
I have tested on my browser and with various screen sizes, it calculates the top and left on hover and adjust the position whenever the track is hovered.
=> Responsivity of track page

src/generator/backend/tracks.tpl
fixes this https://github.com/fossasia/open-event-webapp/issues/320 
=> use full path with https in tracks.tpl includes

src/generator/backend/tracks.tpl
Ressolved  this https://github.com/fossasia/open-event-webapp/issues/322
=> fix popBox() to work in Firefox

package.json
=> add connect-domain dependency

package.json, spec/serverSpec.js
@championswimmer @mariobehling  Related Issue #326
Steps to run, It will do basic integration for running test via Jasmine.
1. npm start run
2. npm start tester
=> Added Jasmine with Jasmine-node

src/generator/www/index.html
@mariobehling @championswimmer  Solved Issue #333 
Please consider the snapshot attached 
**MOBILE**
**TABLET**
**BIGGER SCREEN**
=> Layout fixed

.gitignore, src/generator/backend/assets/js/popover.js
Same as this fix https://github.com/fossasia/open-event-webapp/pull/323 
Had gotten omitted during refactor
=> refix popBox in firefox

src/generator/backend/generator.js
@championswimmer  It will solve issue #339
=> Removed dead functions

package.json, test/spec/serverSpec.js
@mariobehling  @championswimmer  Issue #352 
After Fix
=> Node Test Error Solved

mockjson/sessions.json, src/generator/backend/fold.js, src/generator/backend/generator.js, src/generator/backend/rooms.tpl
ISSUE #345
@championswimmer @mariobehling , Check this Markup.
=> Markup for Room Page

mockjson/microlocations.json, package.json, src/generator/backend/dist.js, src/generator/backend/fold.js, src/generator/backend/generator.js
=> Download audio files locally when rendering live 

src/generator/backend/dist.js
@championswimmer  Check and merge please.
=> Fix Bug for Live/Preview

src/generator/backend/rooms.tpl
Issue Related #362
Before
After
=> Fixing Layout for Room

src/generator/backend/generator.js
redundant calls = more memory. more cpu cycles
bad bad bad
=> make call to getJsonData only once

src/generator/backend/_scss/application.scss, src/generator/backend/rooms.tpl, src/generator/backend/tracks.tpl
@championswimmer It is related to Issue #365
=> Loading Bug and Small fixes

src/generator/www/index.html
=> add option to select download or link mode for assets

package.json, src/generator/backend/dist.js, src/generator/backend/fold.js, src/generator/backend/generator.js
if link mode is chosen then links to external assets
if download mode is chosen then audio/xxxx.mp3 and img/speakers/xxxx.jpg is used
=> Assetmode working

src/generator/backend/_scss/_base/_config.scss, src/generator/backend/_scss/application.scss, src/generator/backend/fold.js, src/generator/backend/generator.js, src/generator/backend/rooms.tpl, src/generator/backend/schedule.tpl, src/generator/backend/speakers.tpl, src/generator/backend/tracks.tpl
Issue Related #371
@mariobehling @championswimmer Check and Merge PLease
=> Speakers Page Added

src/generator/backend/generator.js, src/generator/backend/templates/partials/navbar.hbs, src/generator/backend/templates/rooms.hbs, src/generator/backend/templates/schedule.hbs, src/generator/backend/templates/speakers.hbs, src/generator/backend/templates/tracks.hbs
addresses these issues
https://github.com/fossasia/open-event-webapp/issues/350
https://github.com/fossasia/open-event-webapp/issues/375
=> refactor handlebar templates and make navbar partial

src/generator/backend/_scss/application.scss, src/generator/backend/generator.js, src/generator/backend/rooms.tpl, src/generator/backend/templates/partials/footer.hbs, src/generator/backend/templates/rooms.hbs, src/generator/backend/templates/schedule.hbs, src/generator/backend/templates/speakers.hbs, src/generator/backend/templates/tracks.hbs
Please merge #379 before it.
@championswimmer  @mariobehling  Solved #377 ,This will make common footer template for all, No need to write it again separately in each file.
=> Footer With a single file (footer.hbs)

src/generator/backend/_scss/application.scss, src/generator/backend/templates/schedule.hbs, src/generator/backend/templates/speakers.hbs
Issue related #381
@mariobehling @championswimmer Please check and merge.
=> Biography added to speakers page

src/generator/www/index.html
fixes this issue 
https://github.com/fossasia/open-event-webapp/issues/373
=> make assetmode select work as menu on chrome

mockjson/speakers.json, src/generator/backend/generator.js, src/generator/backend/templates/speakers.hbs
@mariobehling  @championswimmer Issue #387
Parent Issue #334
=> changed Speaker.json according to V2 API

src/generator/backend/fold.js, src/generator/backend/generator.js
=> fix some lint issues

README.md, src/generator/backend/fold.js, src/generator/backend/generator.js
wraps up this old lying issue
https://github.com/fossasia/open-event-webapp/issues/190
=> Codeclimate badge

src/generator/.eslintrc, src/generator/app.js, src/generator/backend/assets/js/popover.js, src/generator/backend/dist.js, src/generator/backend/fold.js
addresses issue https://github.com/fossasia/open-event-webapp/issues/402
=> Fix lint issues

src/generator/backend/_scss/application.scss
=> UX improved : Scrollbar only on hover

src/generator/app.js, src/generator/backend/dist.js, src/generator/www/index.html
@mariobehling  @championswimmer 
Successfully solve issue #336
It also Covers the PR #406.
Please check by uploading only a single zip containing all JSONS.
=> Upload Single Zip instead Multiple Files

mockjson/event.json, src/generator/backend/fold.js, src/generator/backend/generator.js, src/generator/backend/templates/partials/navbar.hbs
solves this issue https://github.com/fossasia/open-event-webapp/issues/410
=> use new social_links format instead of services

.travis.yml
=> add code coverage support

mockjson/event.json, src/generator/backend/fold.js
Issue solved #399 @championswimmer @mariobehling Now event.json is also changed, means all JSONS are according to V2 API
=> replaced event.json according to V2 api

src/generator/backend/fold.js, test/spec/serverSpec.js
=> remove old function and add slugify() in tests

src/generator/backend/fold.js, src/generator/backend/generator.js, src/generator/backend/templates/rooms.hbs, src/generator/backend/templates/schedule.hbs, src/generator/backend/templates/speakers.hbs, src/generator/backend/templates/tracks.hbs
I have added dynamic title tag. If you want to have extra json field do tell me I will update accordingly.
=> Added dynamic html tag to generated pages

src/generator/backend/_scss/_base/_config.scss, src/generator/backend/_scss/_themes/_dark-theme/_dark.scss, src/generator/backend/_scss/_themes/_light-theme/_light.scss, src/generator/backend/_scss/application.scss
@championswimmer @mariobehling  Issue #429 Few UI small fixes will be done in next PR. 
Tracks
Speakers 
Room
=> Dark Theme added 

src/generator/backend/_scss/_themes/_light-theme/_light.scss, src/generator/backend/_scss/application.scss, src/generator/backend/templates/speakers.hbs
Issue solved #436 @championswimmer  Please check and merge.
=> SASS redundancy removed

src/generator/backend/fold.js, test/serverTest.js
=> add test for social links

src/generator/www/index.html
=> fix basic issues of frontend

src/generator/backend/templates/partials/navbar.hbs
this fixes links to track when used from speakers and rooms page 
=> fix track links in navbar

src/generator/app.js, src/generator/backend/dist.js, src/generator/backend/fold.js, src/generator/backend/generator.js
=> Multi user multi site

src/generator/backend/_scss/application.scss, src/generator/backend/templates/partials/footer.hbs, src/generator/backend/templates/partials/navbar.hbs, src/generator/backend/templates/schedule.hbs, src/generator/backend/templates/tracks.hbs
@championswimmer check and merge please Issue Related #460
=> Schedule Link Added , Link made activated on click

package.json, src/generator/app.js
=> Add compression middleware

src/generator/backend/_scss/application.scss, src/generator/backend/templates/schedule.hbs
=> Fixed social links in schedule page and fixes 

src/generator/backend/fold.js, test/serverTest.js
=> increase code coverage

src/generator/app.js, test/serverTest.js
=> add more code coverage

src/generator/backend/dist.js, src/generator/backend/fold.js
This make sure server does not crash if some sessions do not have the `track` property.
(Basically this error : https://github.com/fossasia/open-event-orga-server/issues/1668 ) 
=> add checks for null track error

src/generator/backend/templates/speakers.hbs
=> speaker page updated

src/generator/backend/assets/js/popover.js, src/generator/backend/templates/speakers.hbs
=> Houndci Codacy  issues solved

src/generator/backend/_scss/application.scss, src/generator/backend/templates/rooms.hbs
=> Add Track-titles with colors on Room page

src/generator/backend/templates/partials/navbar.hbs
=> link home to index.html (sessions.html will be separate later)

src/generator/backend/dist.js, src/generator/backend/generator.js, src/generator/www/js/form.js
Mention error explicitly on the front-end rather silently logging them
on server side
=> Mention Errors on the Front End

src/generator/backend/dist.js, src/generator/backend/fold.js, src/generator/backend/generator.js, test/serverTest.js
@mariobehling @championswimmer This solved the issues with sponsors images
-  Both the path of photo  **/images/ and images/** inside  JSON should be handled by the code.
=> Sponsor Images in Zip

src/generator/backend/dist.js
=> fix the json folder path in zip upload

src/generator/www/js/form.js
=> open live preview and download zip from new tab

src/generator/backend/fold.js, src/generator/backend/generator.js, src/generator/backend/templates/event.hbs, src/generator/backend/templates/partials/navbar.hbs, src/generator/backend/templates/rooms.hbs, src/generator/backend/templates/schedule.hbs, src/generator/backend/templates/speakers.hbs, src/generator/backend/templates/tracks.hbs
@championswimmer @mariobehling I will carry out more changes in next PR. Please check and merge this.
=> Added Event page 

package.json, src/generator/backend/generator.js, src/generator/backend/mailer.js
=> send email after website is generated

package.json, src/generator/backend/dist.js, src/generator/backend/fold.js, test/serverTest.js
=> handle relative sponsor and speaker images in the API

src/generator/backend/templates/partials/navbar.hbs
resolves this issue 
https://github.com/fossasia/open-event-webapp/issues/559
@aayusharora please check and merge :) 
=> fix track links on sessions.html anchor tags

src/generator/backend/_scss/application.scss, src/generator/backend/assets/js/popover.js, src/generator/backend/fold.js, src/generator/backend/generator.js, src/generator/backend/templates/event.hbs
Issue Solved #563 #564 #519
@mariobehling @championswimmer  Please check and merge
=> Popover for speakers 

src/generator/backend/generator.js, src/generator/backend/templates/partials/navbar.hbs
=> turn sessions.html to tracks.html, remove old tracks

src/generator/backend/fold.js
fixes this issue 
https://github.com/fossasia/open-event-webapp/issues/583 
@aayusharora  please check
=> Image upload fix

src/generator/backend/fold.js
@championswimmer  After your PR merge still I was not able to have the images. I have fixed it here, Please check and merge.
Issue #583
=> Logical Bug for Zip Images

src/generator/backend/_scss/application.scss, src/generator/backend/fold.js, src/generator/backend/templates/event.hbs
Issue #571  
Updated snapshots
**Sponsor section**
**Removed X-axis scroll**
**Description**
=> Layout fix sponsor section

src/generator/backend/templates/partials/navbar.hbs
solves point no 1 from https://github.com/fossasia/open-event-webapp/issues/594
=> use event name instead of logo if no logo given

src/generator/backend/fold.js, src/generator/backend/templates/event.hbs
- AT -> at
- Thu -> Thursday 
solves point 3 on https://github.com/fossasia/open-event-webapp/issues/594
=> fix date format on frontpage

src/generator/backend/templates/partials/footer.hbs
solved point 6 in https://github.com/fossasia/open-event-webapp/issues/594
=> check license exists in copyright before displaying in footer

src/generator/backend/_scss/_base/_config.scss, src/generator/backend/_scss/application.scss, src/generator/backend/fold.js, src/generator/backend/templates/event.hbs
@mariobehling @championswimmer It solved #575 
Kindly merge #593 before it.
=> Register Option added on Home page

src/generator/backend/templates/schedule.hbs
=> remove sponsors from tracks page as they are in frontpage now

src/backend/generator.js
if fixes this issue 
https://github.com/fossasia/open-event-webapp/issues/604 
=> fix non-slug app names sent in emails

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/partials/navbar.hbs, src/backend/templates/schedule.hbs
=> Day links in schedule

package.json, src/backend/dist.js, src/backend/fold.js
fixes two things - 
- background image and logo not being copied correctly from zip or not downloading from api
- urlencode was encoding the '/' character too. that was wrong and was corrupting some images.
=> fix some issues with images not downloading or copying from zip

src/backend/assets/js/popover.js
@mariobehling @championswimmer Kindly check and merge
Issue #592
>Previous
**- Wrong alignment, No calculation for height of popover.** 
>Now 
**Calculating popover height and adjusting popover dynamically**
=> added dynamic footer 

src/backend/generator.js, src/www/index.html, src/www/js/form.js
=> Add progressbar

src/backend/fold.js
@championswimmer @mariobehling Please merge.
Issue #623
=> background image bug fix

src/backend/_scss/application.scss, src/backend/assets/js/popover.js, src/backend/fold.js, src/backend/templates/event.hbs
@championswimmer @mariobehling  Please merge
Issue #616
=> Responsive issue Roompage and other fixes

src/www/index.html, src/www/js/form.js
Issue #627 
@championswimmer Please Merge
=> progressbar should display after button click

src/backend/_scss/application.scss, src/backend/templates/partials/navbar.hbs
Issue #620 
@championswimmer @mariobehling Please merge this. Created separate issue for last point #629
=> navbar fixes

src/backend/fold.js
The parameter in the API is background_image not background_url
ALso, to check both null and undefined, we must check `!= null`
=> Fix background image

src/backend/assets/dependencies/loklak-fetcher.js, src/backend/fold.js, src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs, src/backend/templates/partials/navbar.hbs
Please merge after merging #634
Issue #629
=> Dont show pages menu without data

src/backend/assets/dependencies/loklak-fetcher.js, src/backend/fold.js, src/backend/templates/event.hbs, src/backend/templates/partials/navbar.hbs
=> Logo Fix, Twitter worked with handle '_'

package.json, src/backend/ftpdeploy.js, src/backend/generator.js, src/www/index.html, src/www/js/form.js
=> add ftp deployment

src/backend/generator.js
=> perform ftp upload only if user has checked ftp option

src/backend/fold.js, src/backend/templates/partials/footer.hbs
The key **license** has been changed to **licence** causing the problem
@mariobehling @championswimmer Solved it please merge
=> Copyright info Corrected

src/backend/templates/event.hbs
Issue #623
@mariobehling  @championswimmer  Please check and merge
=> Image Centered and overlay less dark now

src/backend/assets/js/popover.js
Issue #592
@mariobehling @championswimmer  Please merge
=> popover fix on Mobiles 

src/backend/templates/event.hbs
Issue #590 
@mariobehling @championswimmer Please merge
=> Make Sponsors and Twitter full section

src/backend/fold.js, src/backend/templates/event.hbs
Issue #641 
@mariobehling @championswimmer Please review and merge
Before 
After
=> Correcting Layout for Sponsor section

src/backend/templates/speakers.hbs
Issue https://github.com/fossasia/open-event-webapp/issues/565
It will add room info to popover,
=> added location info to popover

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs
Issue #654 
Now the Track page will render HTML tags when the speaker Bio or session description is written in HTML.
=> Render HTML in Track page

src/backend/assets/js/map.js, src/backend/templates/event.hbs
=> Corrected map and added address location, contact info

src/www/js/form.js
@aayusharora @championswimmer Fixes #657 
Please review and merge of looks good.
=> Allow user to upload only zip files

src/backend/_scss/application.scss, src/backend/assets/js/map.js, src/backend/templates/event.hbs
=> corrected zoom level

.gitignore, package.json, src/app.js, src/www/index.html, src/www/js/form.js
=> fix zip uploads for large zips [STILL TESTING] 

src/backend/assets/js/popover.js
=> fix event variable in firefox

src/app.js, src/backend/dist.js, src/backend/generator.js, src/www/js/form.js
=> show feedback of socketio upload on frontend

src/app.js, src/www/js/form.js
=> show upload percentage correctly

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss, src/backend/fold.js, src/backend/generator.js, src/backend/templates/rooms.hbs, test/serverTest.js
=> Room Page Redesign

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/rooms.hbs
Check it with endpoint http://open-event-dev.herokuapp.com/api/v2/events/9
Issue #668 
**Home**
**Tracks**
**Room**
**Speakers**
=> Webapp working with API end point and minor fixes

src/backend/_scss/application.scss
=> Fix layout footer

src/backend/fold.js
=> Removing Repeated Room names

README.md
=> add components and technologies in readme

src/backend/fold.js, src/backend/templates/event.hbs
=> Featured speakers only on home screen

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss
Issue #674
Consider I have not made it as it is like fossasia.org =>1.  Transparent on top 
2. Semi transparent on scroll.
Instead of this, Here it is only semi-transparent 
Reason:  We only have one logo image provided by user. Fossasia.org uses two logo images one light and other dark to handle it beautifully. Making topbar same as fossasia.org will require a light logo to be visible on overlay.
Image1 
Image2
=> Top bar made semi-transparent

src/backend/fold.js
=> Fix timezone offset

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/generator.js, src/backend/templates/event.hbs, test/serverTest.js
=> Feature Section bugs removed

src/backend/fold.js, src/backend/generator.js, src/backend/templates/event.hbs, test/serverTest.js
=> Dont Create Sponsor Section if No sponsor data is there

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs
=> Add time to left in Venue Page

src/backend/fold.js, src/backend/templates/speakers.hbs
=> speaker page linked with track 

README.md, docs/COMPONENTS.md
=> documentation of components and how final html is formed 

src/backend/templates/speakers.hbs
fixes this issue https://github.com/fossasia/open-event-webapp/issues/670 
=> add standard styling to speakers page

src/backend/templates/event.hbs
Issue #690 
- Solve point1 of mentioned issue, Rearranges sections
=> rearrangement of section

src/backend/_scss/application.scss, src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs
=> Alignment of Home page

README.md, config.json, docs/CONFIGURATIONS.md, src/app.js, src/backend/mailer.js
resolves this https://github.com/fossasia/open-event-webapp/issues/523
=> Configurations

src/backend/fold.js, src/backend/templates/partials/navbar.hbs, src/backend/templates/schedule.hbs
Issue #695 
-The link Home gets active instead of schedule on schedule page **Solved**
-Speaker tag still shows when there is no speaker info. **Solved**
-HTML not rendering in speakers Description. **Solved**
-Time Headings are bolder and not responsive in mobile view **Solved**
@mariobehling @championswimmer Please Merge
=> Fixed issues New Schedule page

src/www/index.html
Fixes #697 
@championswimmer @aayusharora Please test and merge
=> Add lable for zip upload

src/backend/_scss/application.scss, src/backend/templates/event.hbs
Solved https://github.com/fossasia/open-event-webapp/issues/579
@mariobehling Please Check and merge.
=> Make Map Full Container

src/backend/_scss/application.scss, src/backend/templates/event.hbs
=> Twitter Secttion Color and layout corrected

src/backend/assets/js/navbar.js, src/backend/templates/event.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
=> commonify js code and headers

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
@mariobehling @championswimmer Please merge 
Issue #703
=> Design Fixes

src/backend/_scss/application.scss, src/backend/assets/js/popover.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Kindly Merge #708 before this
I was only having one syntax error, which I have solved
Solved #702
@mariobehling @championswimmer Please merge
=> Error In Console solved

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs
=> Added alignment for tracks colors

src/backend/_scss/application.scss
=> Left alignment of speakername

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/speakers.hbs
@mariobehling  @championswimmer  Please close issues 
ISSUE #670 #671 #676 If this looks ok
=> small design fixes

src/backend/fold.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
@mariobehling  @championswimmer  Kindly close ISSUE #717 #715 if it looks good.
=> Linking Room,Track,Session pages to Speakers  and correcting layouts

src/backend/_scss/application.scss
@mariobehling @championswimmer addresses Issue #671
Confirmed Gray color for all content and black for all headings.
=> Added css for making consistency in colors

src/backend/_scss/application.scss, src/backend/templates/event.hbs, src/backend/time.json
resolves https://github.com/fossasia/open-event-webapp/issues/703 
=> same section header class

src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
@aayusharora can you test if it works. ?  
=> fix sharing links

src/backend/assets/js/scroll.js, src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Intends to resolves 2 out of 3 issues in  #701.
- fixes " About page not correctly linked from all pages ".
- fixes "Scroll to top should use scrolling feature"
=> Fix footer menu links issue

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
=> fix speaker name linking issues 

src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs
=> Footer: ticket link now linking to ticket area on start page

src/backend/_scss/application.scss
=> Corrected styling of popover

src/backend/templates/rooms.hbs
fixed https://github.com/fossasia/open-event-webapp/issues/738
=> Fix date link scroll

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs
=> White spaces fixed

src/backend/_scss/application.scss, src/backend/templates/partials/navbar.hbs
cosmetic fixes to navbar in mobile view:
- change color of icon-bar - so that it's more visible on semi-transparent background on HOME page
- add a bit more space between social icons and icon-bar - so that it doesn't look too "crowded"
=> change color of navbar icon-bar and add some space before it

src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs
hide Tickets link if event lacks register URL
add Schedule link to the footer
=> minor layout fixes on the event page

src/backend/fold.js, src/backend/generator.js, src/backend/templates/event.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Take meta author and description from event JSON, instead of using hardcoded values
=> fix meta author and description

rooms.html, schedule.html, speakers.html, tracks.html
=> Updated site

src/backend/fold.js, src/backend/generator.js, src/backend/templates/rooms.hbs
=> Repeated Tracks Removed

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
layout fixes on mobile devices
resolve #752 and #753
=> Mobile layout

src/backend/_scss/application.scss
Intends to resolve #760 .
result:
=> Fix alignment issues in schedule page popover

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs
resolves #762 
screenshots are attached to the issue
=> Schedule page redesign to use expandable blocks

src/backend/templates/rooms.hbs
=> cleanup rooms pages template

src/backend/templates/schedule.hbs
HTML alignment fixes to simplify future maintenance
=> cleanup Schedule page template

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/speakers.hbs
=> fix layout on speakers page

src/backend/templates/schedule.hbs
=> Add tracks legend to the schedule page

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs
=> Spaces adjustment

src/backend/_scss/application.scss, src/backend/templates/speakers.hbs
Intends to resolve #783 .
Result:
=> Show name, affiliation and link on dropdown speakers info

src/backend/_scss/application.scss, src/backend/templates/speakers.hbs
Intends to resolve #791 .
Result:
=> Enhance speaker box

src/backend/templates/rooms.hbs
Reverts fossasia/open-event-webapp#788
and thus resolves #795
=> Revert "Update rooms.hbs"

src/backend/templates/speakers.hbs
=> removing spacing before brackets in speaker box

src/.eslintrc
Change `no-extra-parens` config to pass codeclimate
=> Change extra parens config

package.json, src/backend/generator.js
@mariobehling @championswimmer I was just experimenting with different npm modules and found htmlminifier interesting. 
For the issue https://github.com/fossasia/open-event-webapp/issues/781
Improvements are not much its only 150kb improvement in the size of HTML file for Fossasia Zip, but the improvement can be seen on a large scale when ZIP is very large.
=> Performance Improvements Using Html Minify

src/backend/_scss/application.scss, src/backend/templates/speakers.hbs
=> Speakers page:Use full width of available area for name and company

src/backend/_scss/application.scss, src/backend/templates/event.hbs
Changed the width of the map to `col-md-8` and height to `75vh`
Changes made can be previewed [here](https://magician03.github.io/open-event-webapp/)
=> Updated the width and height of the map

src/backend/templates/partials/navbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
I have removed redundant closing tags and added closing tags for unclosed html tags. Review this and please suggest improvements.
=> closed tags and removed redundant closing tags

.hound.yml, .scss-lint.yml
Writing a .scss.lint.yml file that will allow max-depth: 4
=> Hound config set with scss

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Added Searching Functionality to `speakers` and `rooms` page. @mariobehling @SaptakS please review.
=> Added Searching Functionality

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs
@mariobehling @aayusharora please review.
=> Added Searching Functionality to schedule page

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
@mariobehling @aayusharora i have converted css to scss.
=> Converted css to scss

src/www/css/main.css, src/www/index.html
@mariobehling @aayusharora Design enhancement for issue #820.
=> Design enhancement for issue #820

src/backend/_scss/application.scss, src/backend/templates/speakers.hbs
@mariobehling current changes make the pop-over design look like this.
Please suggest further steps and/or any changes to this.
=> Fixing #801

src/backend/_scss/application.scss
Fixes the issue #831. Screenshots are attached in the issue. Link to the gh-pages
https://princu7.github.io/websiteTest/schedule.html
@mariobehling  @aayusharora  Please review.
=> Fixed the splitting of the datas issue on smaller screens

src/backend/fold.js, src/backend/templates/rooms.hbs
Solves the first four points of the issue #780 .
Link to the updated rooms page
https://princu7.github.io/websiteTest/rooms.html
@mariobehling  @aayusharora  Please review.
=> Added more venue details

src/backend/_scss/application.scss
Solves the issue #815 .
@mariobehling  @aayusharora 
Here is the link to the gh-pages
https://princu7.github.io/websiteTest/speakers.html
=> Made some changes to the application.scss file

src/backend/assets/js/navbar.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Solves the issue #845 and #830.
https://princu7.github.io/websiteTest
@mariobehling  @aayusharora 
Please review it. Thanks
=> Fixes the problem with the session and the speakter links. Also fixes navbar links.

src/backend/templates/rooms.hbs
Added Link icon that shows link on click ![link icon](https://cloud.githubusercontent.com/assets/1583873/18262985/b9cd6a88-7406-11e6-8f0f-369b2486b344.png) (see current tracks page) regarding #780 
@mariobehling Please preview at https://jainaman224.github.io/open-event-webapp/issue780/rooms.html. Thank you.
=> Added Link icon

gh_deploy.sh
@mariobehling  in relation to #859 , forgot to change url of the repo to the fossasia one.
=> change repo for auto generate feature

src/backend/templates/tracks.hbs
@mariobehling Please review this PR at https://jainaman224.github.io/open-event-webapp/issue863/tracks.html regarding #863 .
=> Fixed Searching feature on tracks page

src/backend/assets/js/scroll.js, src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Fixes the issue #866 . 
Test it here
https://princu7.github.io/websiteTest/
Please review. Thanks!!
=> Solved the line issue and the scroll issue

.gitignore, cli.js, config.json, docs/INSTALLATION_LOCAL.md, src/backend/dist.js, test/serverTest.js
=> Add proxy option to config.json for local machines behind a proxy

src/backend/dist.js, src/backend/fold.js, src/backend/generator.js, test/serverTest.js
Resolves #874 completely.
From this PR on, the webapp is fully and properly functional including the download capabilities.
@mariobehling Please review.
=> make all file downloads synchronous

src/app.js, src/backend/buildlogger.js, src/backend/dist.js, src/backend/generator.js, src/backend/mailer.js, src/www/index.html, src/www/js/form.js
@mariobehling  Solves the issue #819. I did the changes that you mentioned. The -logs- is now a link instead of an button and the default option is to hide the logs and only show them when the user select them. You can test the app here
https://salty-basin-93311.herokuapp.com/
Here are the updated screenshots
=> Added support for the build logs

src/backend/fold.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Attempts to resolves #876 and #891 .
Head on to http://shubhamp.in/ots/ for a demo :smiley: .
@mariobehling In my opinion, it is better to stick to the default html5 player because of the stability and more controls it provides.
=> Add audio tags and reposition audio player

test/serverTest.js
After the recent commits corrected a bug in the code, the tests were temporarily disabled in order to let the app run. I have modified the unit tests to go along with the current structure of the code. 
@mariobehling @aayusharora  Please test and review. Thanks!!
=> Made the unit tests to work again

package.json, src/backend/dist.js, src/backend/fold.js, src/backend/generator.js
@mariobehling  Solves the issue #890 . App Used to get stuck or throw an error on upload of large sample zips like OTS16.  Here are the screenshots
Now the local upload of the sample works!!
Since the whole sample site can't be run on github, here is a working demo of the site created from the zip upload of the OTS sample from the local machine
https://princu7.github.io/OTS/
Also refactor some old code and fixes indentation issues. Please review. Thanks!!
=> Fixing the problem with the zip upload of the OTS16 sample

src/backend/_scss/application.scss
@mariobehling 
resolve #822 .
For demo visit https://shubham-padia.github.io/open-event-webapp/ .
=> Avoid internal scroll bars in small resolutions/mobile screens

src/backend/_scss/application.scss
=> Small hover fix 

src/backend/_scss/application.scss, src/backend/assets/js/popover.js, src/backend/templates/speakers.hbs
@mariobehling resolves #534 .
demo: https://shubham-padia.github.io/open-event-webapp/speakers.html
=> make popover work on apple devices 

src/backend/dist.js, src/backend/generator.js
Issue #897 
@mariobehling Kindly merge this.
=> Bug: Critical fix to run app

src/backend/dist.js
Issue #899 
@mariobehling Kindly merge this.
=> Logical Error Fixed

src/backend/_scss/application.scss
@alexagr  resolves #534 finally !!
@mariobehling please review
=> make popover work for ipads

config.json, package.json, src/app.js, src/backend/generator.js, src/backend/mailer.js, src/www/js/form.js
@solves the issue #509 
@mariobehling @aayusharora 
Please test and review.  You can try the app at
https://warm-lake-95173.herokuapp.com
Thank you.
=> Upload of event folder and sending email to the user containing the link

package.json, src/backend/dist.js
Provides an alternative way to solve the issue #899.
=> Uses aync library for copying of the contents of the zip folder

.eslintrc, src/app.js
=> move generator require to the top

README.md
Corrected the directory location of the unit test mentioned in the documentation
=> Fixes #918: Corrected path of unit test

docs/INSTALLATION_GOOGLE.md
Fixes #922 
Provides clear guidelines to use Google Cloud Console and Cloud SDK on the terminal to deploy the Open Event Web App on Google Cloud
=> Rewrote INSTALLATION_GOOGLE.md documentation

docs/INSTALLATION_HEROKU.md
Added instructions for deploying open-event-webapp on heroku
=> Added instructions for deploying open-event-webapp on heroku

src/backend/templates/tracks.hbs
fixes #932 .
https://shubham-padia.github.io/open-event-webapp/tracks.html
=> Fix: tracknames reiterating twice on the tracks page

src/www/css/main.css, src/www/index.html, src/www/js/form.js
Solving #840 
Please provide me feedback for any improvements
=> Implementing progress bar for uploading zip 

src/backend/mailer.js
Used encodeURIComponent instead of replace function #927
=> Used URI Component in the mail sent to the user

src/backend/_scss/application.scss
This PR contains the fix to #940
=> fixed title in tracks page

src/backend/_scss/_base/_config.scss
=> Change navbar color and opacity

src/backend/templates/schedule.hbs
@aayusharora  @mariobehling Fixes the high priority issue #953. Sessions on schedule page were not opening on clicking them. Please review. Here is the live link
http://princu7.github.io/websiteTest
=> Fixed schedule page

src/backend/assets/dependencies/loklak-fetcher.js, src/backend/assets/dependencies/tweets.js
Fixes #961 
Hi, here you can see a preview: https://obscure-escarpment-32909.herokuapp.com/
When Loklak doesn't get any tweet, and when the webpage catches that error, it tells to the user that there are no available tweets.
Here are some photos
I hope you like,
Cheers! 😄
=> Error handling for tweets

src/backend/generator.js
Fixes #956 app crashing if uploaded zip is invalid and not contains required json or files. 
Live Demo - https://openevent-app.herokuapp.com/
=> fixed #956 App crashes when invalid zip

src/backend/_scss/_base/_config.scss
Reverts fossasia/open-event-webapp#944
=> Revert "Change navbar color and opacity"

src/backend/_scss/application.scss, src/backend/assets/js/tabs.js, src/backend/templates/tracks.hbs
Here is the live preview of, the navbar on a site which gets generated:
https://cosmiccoder96.github.io/open-event-webapp/tracks.html
@aayusharora It doesn't cover much of the area , in smaller devices, rather is scrollable.
=> Fixes #954 : Addition of a Navbar for tracks

src/backend/dist.js, src/backend/generator.js, src/www/js/form.js
fix #969 
Live at https://openevent-app.herokuapp.com/
Steps to verify:
1. Try to upload any corrupt zip (just rename any file to .zip) or try any file other than zip. 
2. You can see an error message.
=> fix #969 handle currupted zip

src/www/css/main.css, src/www/index.html, src/www/js/form.js
Improving logs shown on generating app. See #976
=> logs view improvement

src/www/index.html
Fixes #981 Reducing whitespace and buttons alignment.
=> white space fix and buttons alignment

src/backend/dist.js
Working on #960 
Tried working on sponsors images. I would like to get this code reviewed. Will add support for speaker images.
=> Scale Speakers and Sponsor images

src/backend/_scss/application.scss
Improved the design of search bar on speakers page for small resolution.
=> fixes 986 improves the search bar design

.eslintrc, src/backend/_scss/application.scss, src/backend/assets/js/scroll.js, src/backend/templates/tracks.hbs
It adds a minimalistic scroll to top button which appears only if the user starts scrolling.
Here is a preview: 
and here is a screenshot on mobile interfaces
Live preview is available at : 
https://cosmiccoder96.github.io/open-event-webapp/tracks.html
@aayusharora @Princu7 Please review
=> Fixes #977: adds scroll to top button

src/backend/templates/speakers.hbs
Adds auto scroll to the speaker for which the link was clicked.
=> Improved links leading to speakers page #988

src/backend/_scss/application.scss, src/backend/generator.js, src/backend/templates/event.hbs, src/backend/templates/partials/scroll.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
This fixes #997 adds scroll to top button on all the pages.
@aayusharora Please review.
=> Adds scroll button to all the pages

docs/INSTALLATION_HEROKU.md, docs/INSTALLATION_LOCAL.md
Heroku app installation guide is completed to give the full steps as others server heroku installation guide.
[Link_to_edit](https://github.com/meets2tarun/open-event-webapp/blob/development/docs/INSTALLATION_HEROKU.md)
Local Machine deployment guide is edited to rectify the error if one get. 
[Link_to_edit](https://github.com/meets2tarun/open-event-webapp/blob/development/docs/INSTALLATION_LOCAL.md)
=> Edit the documentation

config.json
=> Changed sent from email id

src/backend/dist.js
=> Revert "Fixed the hanging of the app while generating the website of the Ehea…"

src/backend/dist.js
Fixes the issue #1014 properly.
Screenshots
@aayusharora Please review again. It should work fine :)
=> fixed the hanging of the app at the extracting sponsors image step

src/www/js/form.js
@mariobehling @aayusharora @Princu7 
Please review the code.
Live demo at 
=> fixes #1007 restricts only zip to be uploaded

src/www/index.html
added autofocus in the email field of the web-app generator page.
=> adding autofocus to email input field

src/www/js/form.js
@mariobehling @Princu7 @aayusharora 
Please review.
Adds:
After the webapp is generated the "Generate webapp" button is disabled.
Link for demo
=> Disables generated button after generation

src/backend/generator.js, src/backend/templates/partials/subnavbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Live preview at : 
http://cosmiccoder96.github.io/open-event-webapp/
=> Issue #998: Implements navbar on rooms page

src/www/js/form.js
Fixes #1005 
@mariobehling @aayusharora @Princu7 
Please review.
=> hides download and preview button after clicking X

src/app.js, src/backend/generator.js, src/www/js/form.js
#952 Solved
Now the website build is canceled on pressing the cancel button. There also should not be any problem with multiple users.
=> Fixed Cancel Generation Issue

src/backend/_scss/application.scss, src/backend/assets/js/tabs.js
@mariobehling @aayusharora @Princu7 
Please review.
This solves the issue and improves the UX on mobile devices.
=> solves #1027 improves navbar

src/app.js, src/backend/generator.js, src/www/js/form.js
The generation process behaves abnormally on 70%.
Reverts fossasia/open-event-webapp#1031
=> Revert "Fixed Cancel Generation Issue"

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
solved #1019
@aayusharora please check
=> Enhanced tabbed browsing

gh_deploy.sh
=> updated deploy.sh

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss, src/backend/assets/js/social.js, src/backend/generator.js, src/backend/templates/event.hbs, src/backend/templates/partials/social.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Adds social sharing feature to the generated web app.
@mariobehling @aayusharora @Princu7 Please review.
=> Adds social share buttons to the web app #1010

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Issue #1053 
`<a>` is not a good approach here.
=> Revert "Enhanced tabbed browsing"

src/backend/dist.js, src/backend/fold.js, src/backend/generator.js
Fixes #1056 #1050. 
* Corrects the API endpoint of the App Generator.
* Corrects the issues related to the scaling and resizing of images.
* The FOSSASIA 2017 event site is generated successfully. The size of the zip is reduced from 145MB to around 30MB approx.
```
Test-Server: https://peaceful-earth-19050.herokuapp.com
API-Endpoint for FOSSASIA 2017: https://eventyay.com/api/v1/events/6
```
@aayusharora @mariobehling Please review. Thanks!!
=> Correct the API endpoint functioning of the webapp

src/backend/_scss/application.scss
Improves the date buttons on mobile.
Demo link
http://open-event-web-appp.herokuapp.com/
@aayusharora @Princu7 @mariobehling please review this.
=> improves UI for mobile #1043

src/backend/fold.js
This solves #1064.
I have checked and tested using API https://eventyay.com/api/v1/events/6
Screenshot:
Live Demo:
@mariobehling @aayusharora @Princu7 Please review this. Thanks!
=> fixes  #1064 : sorted dates for schedule and rooms page

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/tracks.hbs
fixes #1069 
As for the speaker images, I was unable to reproduce the issue and tested various speakers on different screen sizes.
@mariobehling Can you give a specific instance where this occurred.
=> Fixes colour of links on speakers page

src/backend/fold.js, src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Fixes #1077 #1061 
Test Server:
http://peaceful-earth-19050.herokuapp.com/
=> Speaker and Sessions Description updated

src/www/js/deployProgress.js
Corrects the deploy URL from the previous PR. Sorry
=> Corrected the deploy URL

src/backend/_scss/application.scss, src/backend/generator.js, src/backend/templates/speakers.hbs
Improved Speaker Page . Resolved Issue #1078 . Please review and merge
@aayusharora Please check the links color and underlining and I have also fixed empty data issue
=> Improved Speakers page

src/backend/mailer.js
=> corrected information in mail

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/rooms.hbs
Fixes #1090 and #1081 
@mariobehling @aayusharora Please review this.
Test server link:
Screenshot
=> Improves speakers on rooms page and changes navbar color to black

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
@mariobehling @aayusharora 
Please review
Demo:
https://www.useloom.com/share/123960c3b7d84d929fadff98a88f2b2f
Test server:
=> fixes #1089 improves links in divs

src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Improves the links to the session, for all the pages and the view of the session when using the links.
Test server 
@mariobehling @aayusharora Please review.
=> fixes #1098: improves the links

src/backend/fold.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Solves #1104 
- Adds end time to all sessions in rooms, schedule and tracks page
- Improves direct links in tracks page 
@mariobehling @aayusharora @Princu7 Please review. Thanks 
Test server :
Screenshots :
=> Fixes : #1104 & #1099 adds end time and improves URLs in tracks page

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs
Fixes #1099 improves links for schedule page, Fixes #1110 for rooms page
test server:
@mariobehling @aayusharora @Princu7 Please review. Thanks.
=> Fixes the schedule page links and sessions in rooms page

src/backend/templates/tracks.hbs
Signed-off-by: Rishabh Khanna <rishabhkhanna777@gmail.com>
=> Fixed issue #1100

src/backend/_scss/application.scss, src/backend/templates/partials/navbar.hbs, src/www/js/translator.js
fixed #1002 , deployed on Heroku
https://guarded-inlet-13297.herokuapp.com/
@aayusharora sorry I was late due to exams in college :)
=> added language support

src/backend/templates/rooms.hbs
live gh-page is here :-
https://rishabhk07.github.io/open-gh/rooms.html
=> Issue #1100 Fix extended to Rooms page

src/backend/_scss/application.scss, src/backend/templates/partials/navbar.hbs, src/www/js/translator.js
Reverts fossasia/open-event-webapp#1108
=> Revert "added language support"

src/backend/mailer.js
Fixes #1066.
Removes the cryptic name of the download zip file.
* Test Server: 
http://secure-meadow-20680.herokuapp.com/
@aayusharora @mariobehling Please review. Thanks
=> Changed cryptic name of the downloaded zip file to its original name

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss, src/backend/assets/js/social.js, src/backend/dist.js, src/backend/generator.js, src/backend/templates/partials/social.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Solves #1055 Adds share feature to the generated web-app.
Screenshot:
Test server:
@mariobehling @aayusharora @Princu7 Please review thanks.
=> Adds share feature to webapp

src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Fixes #1111.
* Solves the problem of bookmarking sessions on the Tracks page.
* Indents the code according to the standard convention on the tracks and rooms page
Live `gh-pages` link:
https://princu7.github.io/eventSiteWebApp/tracks.html
=> Fixes bookmark problem on tracks page

src/backend/fold.js, test/serverTest.js
Sorted sponsors list according to level.
check :- https://open-event-webapp1.herokuapp.com/
=> #1068 Display sponsors according to their level

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Fixes #1088 and #1129 
Adds avatar for sessions and fixes buggy scroll for morzilla.
Test server:
@mariobehling @aayusharora Please review. Thanks
Screenshots
**Before**
**After**
=> Adds avatar to speakers and improves scroll

src/backend/dist.js, src/backend/templates/event.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Solves #1138 and #1135 .
Test server:
Adds lazy load to all the pages please check the Screenshots:
**Tracks page**
**Rooms page**
**Schedule page**
**Searchable speakers on schedule page**
=> Adds searchable speaker and adds lazy load to all the pages

src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
I tried to fix the spacing before the company of speakers. :)
=> #1140 : fix the space missing before company of speakers

src/backend/_scss/application.scss
Results:-
[https://dinesh-sirvi.github.io/open-webapp/](https://dinesh-sirvi.github.io/open-webapp/)
=> #1146 Schedule: Buttons for days and "Show Starred" should have same size occupying 100% of width

src/www/js/form.js
fixed inactive webapp generate button if user enter a wrong email address.
=> #1029: fixed inactive generate button on entering wrond email address

src/backend/_scss/application.scss
This is how it looks now.  Think it fixes #1136
=> #1136 : tweet overflow on homepage

src/backend/templates/event.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
added preloading of assets in web app to enhance the performance on slow networks.
demo can be found here - https://secret-forest-50930.herokuapp.com/
on regular 3g networks-
on regular 2g networks-
the performance increases on slower networks.
=> #1134: added preloading of assets

src/backend/templates/event.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
fixed images not showing on tracks ,home and other pages issue.
test server- https://damp-fjord-94767.herokuapp.com/
=> #1164: fixed images not showing issue

src/backend/dist.js, src/backend/fold.js, src/backend/generator.js
Fixes #1122
- Converts background image to jpg
- Reduces the size of the image by 8x.
- Size is down to 226kb from 1.8mb
Test server :
Demo pages :
https://geekyd.github.io/eventApplication/
=> Optimises background image and reduces the size

src/backend/assets/js/jquery.lazyload.js, src/backend/templates/event.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Adds improved lazy load to the webapp. Previously the lazy load enabled the web app to load the images when they are present in the viewport. This PR improves the image process of the lazy load.
- Loads the image before they come in the viewport, loads the picture faster with scroll.
- Makes the app faster with lazy load.
@mariobehling @aayusharora @Princu7 Please review the performance of the web-app.
Demo link : 
https://geekyd.github.io/eventApplication
=> Adds improved lazy load to the webapp

src/www/deploy.html
Fix for #1173 . Opinions? @Princu7
=> #1173 : add a link to website generator

README.md
Fixes #1193 
Changes: Adds information about gulpfile.js to the documentation of the project.
=> Adds gulpfile.js details to documentation

src/backend/fold.js
Fixes #1169 .
Screenshot : 
Previous : 
After :
=> #1169 : sort speaker sessions

src/www/deploy.html
Fixes #1194 . Just changed the position of the info section to make it work.
Screenshot :
=> #1194 : Fix disappearing of logs

src/backend/fold.js, src/backend/templates/tracks.hbs
Fixes #1138 
Improves the tracks page and fixes the date buttons while search.
Demo : 
https://geekyd.github.io/eventApplication/tracks.html
@mariobehling @aayusharora @Princu7 Please review and suggest other options. Thanks.
=> Improves tracks page #1138

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Fixes #1192 
**Changes**
Synchronizes the bookmarked sessions on all the pages of the event site. If the user bookmarks a session on the tracks page, then this change will be reflected on the other pages as well. The session bookmarked on a particular page will remain bookmarked on the other pages as well. The scope of the sessions starred  are global now.
**Demo-Link**
https://princu7.github.io/eventSiteWebApp/
=> Synchronizes bookmarks on all the pages

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Fixes #1208 
Changes: Improves the layout of sessions in tracks and rooms page.
**Previous design**
**Screenshots for the change:** 
@mariobehling @aayusharora @Princu7 Please review this. Thanks
=> Improves sessions in tracks and rooms page

src/backend/fold.js
Fixes #1118
* Earlier, the unscheduled sessions showed up on the generated website
* This pull request fixes this problem and only shows those sessions which have been scheduled by the organizer
* The decision regarding whether a session has been scheduled is being done on the microlocation field of the session. If the field is null, then it means that the session is unscheduled and vice-versa.
* Deployed site: https://princu7.github.io/eventSiteWebApp
* Test Server: http://secure-meadow-20680.herokuapp.com
@aayusharora @mariobehling Please Review.
=> Added microlocation in fold by tracks

src/backend/_scss/application.scss
=> fix hover on speakers page

src/backend/_scss/_base/_config.scss, src/backend/_scss/_themes/_dark-theme/_dark.scss, src/backend/_scss/application.scss, src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs, src/backend/templates/partials/navbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Fixed #990 (c)
@aayusharora please review
=> Removing inline CSS from handlebars and adding it to SASS

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs
Fixes #1215
Changes: Implements a new view in schedule page for viewing the sessions. The user can now switch between the list and calendar(Grid) view using the toggle buttons. 
Demo server :
@mariobehling @aayusharora @Princu7 Please review this. Thanks :)
=> Adds calendar view to schedule page

package.json, src/app.js, src/www/index.html, src/www/js/form.js, src/www/js/socket.io-stream.js
Fixes #952
**Changes**:
* The zip file continued to upload to server even after pressing the cancel button leading to wastage of bandwidth and inability to upload a new zip file until the first file finished uploading.
* It was due to internal implementation of `socket-io-file-upload` library. Made some changes and now using the `socket-io-stream` library.
* Test Server : http://secure-meadow-20680.herokuapp.com/
**Demonstration for the changes**: 
I created a video demo to demonstrate the changes
https://www.useloom.com/share/805184de385c45c3b2d7adfda48d8615
Excuse my slow internet connection :)
=> Fixes the zip upload problem

src/backend/assets/js/scroll.js
Fixes #1235 
**Changes**: Increased the scroll speed on all the pages of the generated web site.
**Live Link**:
https://princu7.github.io/eventSiteWebApp/
@aayusharora @mariobehling Please review. Check if the speed is suitable enough or should we increase it more.
=> Increased the scroll speed

src/backend/_scss/application.scss
Fixes #1231 . @mariobehling Please review.
Screenshots for change : 
Previous : 
After : 
Pills : 
Buttons :
=> #1231 : fix the disalignment and missing spaces

cli.js
Fixes #1243 
Changes: Reverts the source for generating gh-pages to FOSSASIA Summit
@mariobehling @aayusharora Please merge this. Thanks
=> Changes the source of gh-pages to FOSSASIA Summit

src/backend/assets/dependencies/loklak-fetcher.js
Fixes #1229 
Changes: Changes the query format from eg `fossasia%20from:fossasia` to `fossasia&from:fossasia`. Also loads the tweets over `HTTPS` for loading the tweets for urls using HTTP.
Demo: https://geekyd.github.io/eventApplication
@mariobehling @aayusharora @Princu7 Please review it. Thanks
=> Fixes tweets for app following new loklak api and loads tweets over HTTPS

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/templates/schedule.hbs
Fixes #1256 
Changes: Computes the width adjustment for calendar view while generation of the web app and removes the width adjustment code from schedule.hbs. 
Demo: 
=> Improves performance of calendar view

src/backend/_scss/application.scss, src/backend/assets/js/tabs.js, src/backend/templates/partials/subnavbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Fixes #1259 
Changes: Changes behaviour of day buttons in tracks and rooms page. Removes top day buttons. 
Aligns date in calendar view to make it consistent with list view.
Demo link: https://geekyd.github.io/eventApplication
=> Changes behavior of day buttons in tracks & rooms

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Fixes #1266 
Changes: Improves loading speed of schedule, tracks and rooms page by replacing the `display()` function which is triggered on first load with `initPage()` which iterates over array instead on DOM objects to add stars to all bookmarked sessions .
Demo : 
https://geekyd.github.io/eventApplication
=> Improves loding speed of all pages

src/backend/_scss/application.scss, src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
solves [c] #990 
Changes: Removes inline css from all the pages and adds to application.scss.
Demo:
Server: https://open-event-web-appp.herokuapp.com
gh-pages: https://geekyd.github.io/eventApplication/
=> Removes inline css from all pages

src/backend/_scss/application.scss, src/backend/templates/partials/subnavbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
search) along with full utilization of screen space.
**Fixes** #1265 
**Changes**:
* All the different buttons(list, view, calendar and search bar) are aligned in a single row and the full width of the screen is utilized for showing the date navbar and the buttons.
* Change "Show Starred" to "Starred" and "Show All" to "All".
* The buttons are responsive and behave nicely on different screen sizes.
* Removes the redundant and extra classes written for the search and the filter bar.
* Schedule Page
* Rooms Page
**Demo Link**
* Event Site  : http://princu7.github.io/eventSiteWebApp
* Server : http://secure-meadow-20680.herokuapp.com
@mariobehling @aayusharora @geekyd Please Review. Thanks!!
=> Improve the alignment of different buttons(list, calendar, starred,

src/backend/templates/partials/subnavbar.hbs
Fixes #1283 
Changes: Adds correct Url of rooms to the subnavbar
Link :
https://geekyd.github.io/eventApplication/rooms.html
@mariobehling @aayusharora @Princu7 Please review.
=> Adds correct url of rooms to subnavbar

.travis.yml, config.json, npm-shrinkwrap.json, package.json, src/backend/mailer.js
Fixes #1295 
**Changes**: 
* The problem was occurring due to the outdated version of the Sendgrid which didn't support Promises natively. Upped the version to the latest.
* Changed Sendgrid to the default option for sending email
The Response code is 202
=> Fixed the crashing of app when selecting Sengrid for sending emails

src/backend/assets/dependencies/tweets.js, src/backend/assets/js/map.js, src/backend/assets/js/navbar.js, src/backend/assets/js/popover.js, src/backend/assets/js/scroll.js, src/backend/deploy.js, src/backend/dist.js, src/backend/fold.js, src/backend/generator.js, src/backend/gulpfile.js, src/backend/mailer.js, src/www/js/form.js, test/serverTest.js
**Partly Fixes** #1297 
**Changes**:
Formatted the code and indented it properly. The work is still not complete. Handlebars and HTML files are still left. Will work on them next. 
**Deployment Link**:- http://secure-meadow-20680.herokuapp.com
=> Format the code properly and improve indentation.

src/selenium/basePage.js, src/selenium/eventPage.js, test/serverTest.js
Fixes #1312 
Changes:
* Implements Selenium Page Object model for better structure, readability, maintainability of functional tests written for the website.
* No additional tests are written. Just the existing one has been modified to follow the model.
Sample Test Video: The video is short and not interesting due to the lesser number of tests currently. It will become better with added tests.
https://saucelabs.com/beta/tests/caa07dfbfca94e7d80cb2100742d4daf/watch#6
@aayusharora @geekyd Please review. Thanks!!
=> Incorporated Selenium Page Object Model into Testing

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Fixes #[1329]
Changes: Changed the Search Box UI
Before Changes:
[https://demolp.github.io/OSCAL_2017/](https://demolp.github.io/OSCAL_2017/)
Website After Changes:
[https://demolp.github.io/OSCAL2017new/schedule.html](https://demolp.github.io/OSCAL2017new/schedule.html)
=> Improved Search Box UI

src/backend/deploy.js
Fixes #1334 
Changes:
* Made the automatic deploy to Github work again. The problem was arising due to the recent change in the API specification of a library being used in the project. Found and fixed it and the problem is solved.
**Server Link**: http://secure-meadow-20680.herokuapp.com
=> Fixes the issue with the automatic deployment to Github feature.

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs
Fixes #1315, #1323 
**Changes**: 
Improved the UI of the sub-navbar on the schedule page
* Removed blue color of the links
* Highlight the date selected
**Test-Link**:
http://princu7.github.io/open-event-webapp
@aayusharora @geekyd @mariobehling Please review. Thanks!!
=> Improve the subnavbar UI on the schedule page

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs
Partially Fixes Issue #1373 
**Changes**:
* Eliminates image hopping/animation flicker when the session element is expanded and collapsed.
* Bootstrap collapse class is used for transition. It has a fix interval so the elements which are long will appear to have a faster animation (to fit in the time of transition) while the elements which are short will have a bit slower animation.
**GIF!**
**Test Server**:-
=> Fix the image hopping/animation flicker issue on schedule page

src/backend/_scss/application.scss, src/backend/templates/event.hbs
Partially fixes #1337 
Changes: Added sponsor names along with sponsor images
@aayusharora @Princu7 please review.
=> Sponsor names added

src/backend/_scss/application.scss, src/backend/assets/js/session.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
**Partially Fixes** the parent issue #1374
**Changes**:
* Removes the image flickering issue on tracks page.
* Improves the animation and keep it in accordance with the tracks page
**GIF**: 
**Test Links**
https://princu7.github.io/open-event-webapp
**Please Merge after #1375**. Commit of that PR is included here because it was very difficult to separate them.
=> Made the animation on tracks pages smooth

src/selenium/basePage.js, src/selenium/trackPage.js, test/serverTest.js
Partially Fixes the issue #1311
Changes: 
* Add Session Bookmark test on the tracks page
@aayusharora @geekyd @sumedh123 @CosmicCoder96 @anu-007 Please review. Thanks!!
=> Add Session Bookmark test on the tracks page

src/backend/_scss/application.scss
Fixes #1370 
**Changes**: 
* Fixes the appearance of the placeholder text inside the search bar on the speaker's page and makes it uniform across all the browsers.
* Mozilla Firefox
* Chromium Based browser
@aayusharora @geekyd @sumedh123 @CosmicCoder96 @arp95 @mahikaw Please review. Thanks :)
=> Improve the appearance of placeholder text in search bar on speaker's page in different browsers

src/backend/templates/rooms.hbs
Fixes #1373 Completely
**Changes**:
* Removes the image hopping and animation flicker on the rooms page too!
**GIF**
**Test Links**
http://princu7.github.io/open-event-webapp
=> Fix the flicker animation on the rooms page and image hopping issue

src/selenium/basePage.js, test/serverTest.js
Partially Fixes the parent issue #1311 
Changes:
* Checks whether the down button which enables the user to go to the top of page on click is working fine or not.
**Sauce Video for Demonstration**
https://saucelabs.com/beta/tests/f69ef4b984f948fdad113a29af099854/watch#255
@aayusharora @geekyd @mahikaw @arp95 @sumedh123 @anu-007 Please review. Thanks!!
=> Selenium test for checking the functionality of the down button

src/backend/templates/speakers.hbs, src/selenium/basePage.js, src/selenium/speakerPage.js, test/serverTest.js
**Partially** fixes the parent issue #1311 
**Changes**:
* Checks whether the normal search functionality is working on all the pages or not.
https://saucelabs.com/beta/tests/3b2e798f96824b14986dd423c7cb5806/watch#345
@aayusharora @geekyd @anu-007 @sumedh123 @arp95 @mahikaw Please review. Thanks :)
=> Selenium Test for Checking Search functionality on all the page

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs, src/selenium/trackPage.js, test/serverTest.js
**Partially** fixes the parent issue #1311 
**Changes**:
* Adds Selenium tests for checking the collapsing of session elements on tracks pages.
* An id called `event-title` was being incorrectly used as a class since it was applied on all the session elements. Corrected that. Was necessary for Selenium Tests.
**Video For Demonstration**
https://saucelabs.com/beta/tests/e3b97f1adef743bd95b2b49643c436db/watch#293
=> Selenium test for checking collapsing of session elements on Tracks Pages.

src/backend/templates/schedule.hbs, src/selenium/roomPage.js, src/selenium/schedulePage.js, src/selenium/trackPage.js, test/serverTest.js
**Partially** fixes the parent issue #1311 
**Changes**:
* Checks the session elements collapse behavior is working well on rooms and schedule pages.
**Video for demonstration**
https://saucelabs.com/beta/tests/a713a262a30f4041b81fca36815350e3/watch
@aayusharora @geekyd @sumedh123 @anu-007 @arp95 @mahikaw Please review. Thanks :)
=> Add Selenium tests for checking collapsing of session element on rooms and schedule pages

src/selenium/eventPage.js, test/serverTest.js
Partially fixes the issue #1311 
**Changes**:
* The added tests check whether the tweet section is present or not.
https://saucelabs.com/beta/tests/20dd281c00004f65b89bb053fea96755/watch#280
Not really visible since it is very fast but it is checking for the presence of the tweet section. If it was not there, the test would have failed.
@aayusharora @geekyd @sumedh123 Please review. Thanks :)
=> Added Selenium Test for checking tweet section on the page

src/backend/_scss/application.scss
Fixes #1397 
Changes: Reduced the line spacing
----
@princu @aayusharora Please review and merge
=> Fixed text overflow UI bug

src/selenium/basePage.js, src/selenium/schedulePage.js, src/selenium/trackPage.js, test/serverTest.js
selecting date and toggling mode
**Partially** fixes the parent issue #1311 
**Changes**:
* Adds several tests to check whether the changing of the selected date and toggling the mode of the page (from list to calendar and vice-versa) is working fine.
Please see it here https://saucelabs.com/beta/tests/3fa31423b410452baf586ecc769cd0bc/watch#468
@aayusharora @geekyd @sumedh123 @anu-007 @arp95 @mahikaw Please review. Thanks :)
=> Add Selenium test for checking the behavior of the date divs on

src/selenium/basePage.js, src/selenium/eventPage.js, test/serverTest.js
**Partially** Fixes the parent issue #1311 
**Changes**:
* Checks whether all the links in the navbar and the footer is working or not!
https://saucelabs.com/beta/tests/f9e06fc071e34b32abda00f5db0d08cf/watch
But, it won't be visually available when we are testing the links since it is being done on the backend site through the `request` library!
@aayusharora @geekyd @sumedh123 @arp95 @mahikaw @anu-007 Please review. Thanks :)
=> Selenium test for checking links on navbar and footer

src/backend/templates/tracks.hbs, src/selenium/trackPage.js, test/serverTest.js
**Partially** Fixes the issue #1405 and #1311
**Changes**:
* Search and starred button work well in conjunction now on tracks page.
* Added tests for it.
**Search Then Starred Mode**
**Starred Mode Then Search**
https://saucelabs.com/beta/tests/b9e13baeb03a4a91b9776bc8fc8a914a/watch
@aayusharora @geekyd @sumedh123 @anu-007 Please review. Thanks :)
=> Make search and starred button work correctly together on Tracks page

src/selenium/basePage.js, test/serverTest.js
Partially fixes the issue #1311 
**Changes**:
* Adds Selenium test for checking sub-navbar behavior on tracks and rooms pages.
**Video for Demo**
https://saucelabs.com/beta/tests/bbfdc591da89451fad366a62dff5fe86/watch#626
@aayusharora @geekyd @sumedh123 @anu-007 @mahikaw @arp95 Please review. Thanks :)
=> Add Subnavbar test on tracks and rooms pages

src/backend/dist.js
Fixes #1411 
Changes:
* Increase the quality of the logo output by the generator
Check it here  https://mahikaw.github.io/PyCon2017/
@aayusharora @geekyd @sumedh123 @mahikaw @arp95 Please review. Thanks :)
=> Increase the quality of the logo output by the generator

src/backend/_scss/application.scss, src/backend/templates/partials/navbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs, src/selenium/basePage.js
Fixes #1258
**Changes**:
* Modified search to top bar in mobile view.
**GIF!**
@aayusharora @geekyd @sumedh123 @anu-007 Please review. Thanks :)
=> Modify search to top bar in mobile view

src/backend/templates/rooms.hbs, src/selenium/roomPage.js, test/serverTest.js
tests on the rooms page
Fixes #1405 and partially fixes the issue #1311 
**Changes**:
* Make the search work in conjunction with the starred button and added Selenium tests for it on the rooms page.
**Video For Demo**
https://saucelabs.com/beta/tests/62a42dcf64ad446b94db58331e6cdbb1/watch#684
The test related to this PR start around 7:50 mark
@aayusharora @geekyd @sumedh123 @anu-007 Please review. Thanks :)
=> Make the search work in conjunction with the starred button and added

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs, src/selenium/basePage.js, test/serverTest.js
Partially fixes the issue #1311 
**Changes**:
* Checks for the presence of scrollbars on all the pages of the site on small screen sizes. There is some work left. Speaker section is creating some problem. Also, have to add more sizes for check. Will complete it in another pull request.
* There were scroll bars on schedule page on small mobile size. Fixed it in this PR itself
* Before
* After
https://saucelabs.com/beta/tests/b6676a7e436b467cb1e0f8cc86241bb8/watch#554
@aayusharora @geekyd @sumedh123 @arp95 @mahikaw @anu-007 Please review. Thanks :)
=> Check for scrollbars on index, tracks, schedule and room pages

.yaydoc.yml, docs/INSTALLATION.md, docs/INSTALLATION_AWS_DOCKER.md, docs/INSTALLATION_GOOGLE.md, docs/INSTALLATION_HEROKU.md
Fixes #1420 
Changes: .yaydoc.yml is added for documentation generation and also fixed markdown for proper generation of documentation
=> Fixes #1420 : .yaydoc.yml added to support yaydoc

src/backend/templates/tracks.hbs
Fixes the issue #1317 partially
**Changes**
* Make all the filters (track, search and starred) work in conjunction with one another.
http://princu7.github.io/websiteTest
@aayusharora @geekyd @sumedh123 @harshitagupta30 Please review. Thanks!
=> Make filters (track, search, and starred) work in conjuction with one another

src/backend/_scss/application.scss, src/backend/generator.js, src/backend/templates/partials/navbar.hbs, src/backend/templates/partials/tracklist.hbs, src/backend/templates/tracks.hbs
Partially Fixes the issue #1317 
Changes:
* Adds mobile view of the track name list for filtering sessions
**Demo Website**
http://princu7.github.io/websiteTest
=> Added track name list to the sidebar on smaller screens for filtering sessions

src/backend/_scss/application.scss, src/backend/fold.js, src/backend/generator.js, src/backend/gulpfile.js, src/backend/templates/rooms.hbs, test/serverTest.js
Partially Fixes the issue #1318 
**Changes**:
* Adds room name filter for filtering of sessions on the basis of rooms.
https://princu7.github.io/websiteTest/rooms.html
=> Added Room name list for filtering of sessions based on rooms

src/backend/templates/rooms.hbs
Partially fixes the issue #1318 
Changes: 
* Makes all different filters (starred, search and room filter) work in conjunction with one another on the rooms page.
=> Made all filters work in conjunction with one another on rooms page

src/backend/_scss/application.scss, src/backend/assets/js/icsGen.js, src/backend/generator.js, src/backend/gulpfile.js, src/backend/templates/schedule.hbs
Fixes #1253 
Changes:
* Implement ics/ical to sync with calendars
=>  Implement ICS Download of schedule [WIP]

src/backend/templates/schedule.hbs
code
Fixes #1234 
Changes:
* Enables search function in calendar mode on the schedule page.
* The script code was badly indented. Made it indent properly.
http://princu7.github.io/websiteTest
=> Made Search work in calendar mode on schedule page and indent the script

package.json, src/backend/assets/dependencies/offline.html, src/backend/assets/js/sw.js, src/backend/dist.js, src/backend/generator.js, src/backend/gulpfile.js, src/backend/templates/event.hbs
Fixes #1152, #1218, #1247 
**Changes**
* Adds a service worker from caching and offline loading of pages. WHenever the content of the site is changed, the service worker will get updated again! This is done with the help of hash of the folder of the event website
https://secure-meadow-20680.herokuapp.com
**Test Site**
https://princu7.github.io/websiteTest
@aayusharora @geekyd @sumedh123 @harshitagupta30 Please review. Thanks! More details are in the below comment!
=> Add service worker to the generated site for caching and offline loading of site

npm-shrinkwrap.json, src/backend/dist.js, src/backend/generator.js
Fixes #1440
Changes: 1. return statement added in generator.js so that logs do not show 'jsons downloaded' for wrong end points link.
2.Multiple callbacks removed in dist.js in case of wrong endpoint url.
=> Fixes #1440:App throws error only when wrong endpoint link is encountered.

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs, src/selenium/schedulePage.js, test/serverTest.js
Fixes #1439 #1438 
Changes:
* Changes List View and Calendar View into a single icon changing button.
* Changes download png and download ics buttons into a single drop-down button.
* Modify the existing tests related to the different view buttons.
https://princu7.github.io/websiteTest
@aayusharora @geekyd @sumedh123 @harshitagupta30 @mariobehling Please review. Thanks :)
=> Converted different views (list and calendar) and downloads (png and ics) buttons into single dropdown buttons

src/selenium/basePage.js, test/serverTest.js
Partially fixes the parent issue #1311
Changes:
* Check working of social buttons. Test whether new share window opens on clicking them or not. Do this on the tracks, schedule and the rooms page.
**Video Demo**
https://saucelabs.com/beta/tests/b0c95683907f41cf913286399a83aa9b/watch#1414
The tests around the 36-second mark for checking the working of the social buttons on the tracks page
=> Add Selenium Tests for Checking the working of social buttons.

src/backend/generator.js
Fixes #1450 
Changes: Added if statement in generator.js for correctly displaying the logs.
=>  Error display in logs when the generator is unable to send email.

npm-shrinkwrap.json, src/backend/_scss/application.scss, src/backend/templates/event.hbs
Fixes #1204 
Changes: Added center tag to image in events.hbs
=> Resolves #1204:Center Images on mobile

src/backend/templates/schedule.hbs
Fixes #1445 
Changes: Added star icon and changed javascript in schedule.hbs
Link for reviewing-
https://agbilotia1998.github.io/FOSSASIA-SUMMIT/schedule.html
=> Fixes #1445:Use of icon instead of starred

src/backend/mailer.js
Fixes #1463 
Changes: The local time was sent through email , now the Coordinated Universal Time (UTC) is sent which would remove the time dependency on server.
=> Fixes preview expiry time sent through email.

.codacy.yml
Fixes #1299 
Changes: Added exclude files in .codacy.yml
=> Disabled codacy checks for library files

src/www/js/form.js
=> Removed preview and download button on source change

src/backend/templates/session.hbs
Fixes #1477 
Changes: Changed footer links particularly for session page
=> Fixed footer links on session page

src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
=> Use of icon instead of starred on tracks and rooms page

src/backend/templates/partials/footer.hbs
=> Removed extra spaces in footer.hbs

src/backend/_scss/application.scss
=> Fix multiline overflow in calendar view

src/backend/overviewSite/index.html
Fixes #1491 
Changes: Corrected URL
=> Corrected OSCON webapp URL

test/serverTest.js
Fixes #1499 
Corrected decription to PyCon 17.
=> Corrected pycon17 description

test/serverTest.js
Fixes #1501 
Changes: Added catch statement for error in title test.
=> Added error catch statement

docs/INSTALLATION_LOCAL.md
Corrects grammar in install docs.
Fixes #1519.
=> Fix Bad Grammar

.travis.yml, src/backend/generator.js, src/backend/templates/speakers.hbs, src/selenium/speakerPage.js, test/serverTest.js
Fixes #1467 #1482
Changes: Changed redirect url for sessions on speakers page and wrote selenium test for jumpToSession.
=> Speakers page sessions now redirects to particular session

src/www/js/form.js
Fixes #1524 [Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> Menu closes if clicked outside the Menu-Container

test/serverTest.js
Fixes #1540
Changes: Made changes to serverTest.js
=> Fixed travis for RedHat sample

.travis.yml
=> Fixes travis

README.md
Fixes #1547 
Added Documentation with the links of,
1. https://github.com/fossasia/open-event
2. https://github.com/fossasia/open-event-orga-server
3. https://github.com/fossasia/open-event-android
=> Added Documentation regarding Other related Repositories

src/backend/overviewSite/index.html
=> Corrected RedHat sample url on overview site

src/www/index.html, src/www/js/form.js, test/serverTest.js
Fixes #1535 
Changes: radio button labels are now clickable
You can see the changes made at https://mighty-fjord-71199.herokuapp.com/
=> radio-button-labels-clickable

src/backend/overviewSite/index.html
=> Corrected overview site

src/www/js/form.js
Fixes #1535
Changes: https://mighty-fjord-71199.herokuapp.com/
Correction to #1537 
@agbilotia1998 , @geekyd please see the changes and sorry again on my part for the trouble caused
=> radio labels clickable (#1535)

app.yaml
Fixes #921 
Changes: Changed  app.yaml
Deployment link of cloud:https://open-event-webap-1513522507145.appspot.com/
=> Deployed app on google cloud flex environment

.github/CONTRIBUTING.md
Fixes #1582 
Changes:
- added contributing.md file
see changes here 👍 
https://github.com/YashKumarVerma/open-event-webapp/blob/development/.github/CONTRIBUTING.md
=> Fixes #1582 :  Contributing practices added.

src/www/index.html
Fixes #1587
Changes: Removed "/a>" after -Logs-
Deployment link -https://ancient-brushlands-69889.herokuapp.com/
=> Fixed #1587: Removed "/a>" after -Logs-

.editorconfig
Fixes #1589 
Changes: Created .editorconfig
=> Fixes #1589 : Create .editorconfig

src/www/css/main.css, src/www/index.html
Fixes #1532 
**Changes :**
* Added a container to couple all the UI elements.
**Preview Link : **
https://rocky-stream-65090.herokuapp.com/
=> Fixes #1532 : Added a container to couple all the UI elements.

.travis.yml
Fixes #1619
Changes: 
Refactored travis.yml
=> refactored travis.yml Fixes #1617

src/backend/overviewSite/index.html, test/serverTest.js
Fixes #1610 
Changes: https://parths007.github.io/fossasia11/
=> Fixes#1610 Change Fossasia samples to FOSSASIA Summit

src/www/index.html, src/www/js/form.js
Applied two fixes.
* Removed the `custom-menu-cont` class from `child div`
* Added a `OnLoad()` function which focuses to the email.
=> Fixes #1631 : Fixed rare bug which broke menu bar

src/backend/overviewSite/index.html
Fixes #1652 
Changes:
Fixes favicon issue by changing the href attribute and removing shortcut link.
Live link to test: https://abishekvashok.github.io/open-event-webapp/
=> Fixes favicon issue

docs/INSTALLATION_HEROKU.md
-
-
-
Fixes #1666: Make Docs more informative !!
=> Improvements to Installation with Heroku (Fixes issue: #1666)

src/selenium/eventPage.js, src/selenium/generatorPage.js, src/selenium/roomPage.js, src/selenium/schedulePage.js, src/selenium/trackPage.js
=> Added description for newly added generator tests

src/selenium/speakerPage.js, test/serverTest.js
Fixes #1645 
Parent Issue #1614
=> Added hover on image test for speaker page

src/backend/ftpdeploy.js, src/www/index.html, src/www/js/form.js
=> Added port field in upload-via-ftp input section

test/serverTest.js
=> Changed broken link count in tests of event page

src/backend/templates/partials/tracklist.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
=> Closed tags in template pages.

.travis.yml, src/selenium/schedulePage.js, test/serverTest.js
=> Added test for download dropdown on schedule page

src/selenium/trackPage.js, test/serverTest.js
Fixes #1677 
Parent issue #1614
=> Added test for share link url

.travis.yml
=> Fixes gh-page rebuild issue.

src/backend/_scss/application.scss, src/backend/templates/session.hbs
Fixes #1376 
Changes: Added back button in session.hbs
=> Added back button on single track pages

src/backend/overviewSite/index.html
Corrects mozillaHands16 sample path.
Fixes #1722
=> Corrected mozilla 2016 sample path

.github/ISSUE_TEMPLATE
Commented out instructions in issue template.
Fixes #1717
=> Updated issue template

src/www/index.html
Fixes #1728
-Added list items to `ul` tag
=> Corrected session attributes alignment

src/backend/templates/rooms.hbs, src/backend/templates/tracks.hbs
Fixes : #1740 
Added url to show all sessions of all days.
=> Added option to view all occurences of a track and room

src/backend/_scss/_themes/_dark-theme/_dark.scss, src/backend/_scss/_themes/_light-theme/_light.scss, src/backend/_scss/application.scss
Webapp-generator:- https://ancient-sea-82502.herokuapp.com/
Fixes #1753
=> color scheme improved in dark theme

src/backend/templates/rooms.hbs
Webapp-generator:-https://polar-thicket-79278.herokuapp.com/
preview link:- https://polar-thicket-79278.herokuapp.com/live/preview/kumarsinghshubham32111@gmail.com/F8-FacebookDeveloperConference2017/
Fixes #1758
=> Direct link to session on venue page fix

src/backend/templates/tracks.hbs
Opening `/tracks.html#3014` url scrolls to the card with id=3014 such that it is navbar a bit below the navbar. 
Refers #1755
=> Track scroll fix

src/backend/overviewSite/index.html
Fixed the improper scaling of the images.
Fixes #1735
=> Scaled the images

gh_deploy.sh
- change `gh_token` env variable.
Fixes #1716
=> Fixes #1716 Change GH pages token

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Reduce size of star button and make design of that button same as other buttons on page.
Fixes #1780.
Deployment link (of preview) : https://openeventwebapp.herokuapp.com/live/preview/an@gmail.com/FOSSASIASummit2017/index.html
=> reduce size of star button(#1780)

src/backend/fold_v2.js
Fixes #1785 
Sample:-https://shubham3211.github.io/facebook/schedule.html
=> time error fixed

src/backend/fold_v1.js
sample:-https://shubham3211.github.io/fossasia-2018/
Fixes #1785
=> changes made for api_v1

src/backend/overviewSite/index.html, test/serverTest.js
=> Adds Fossasia 2018 event to overview site and order events according to dates

src/backend/templates/tracks.hbs, src/selenium/trackPage.js
Sample:-https://shubham3211.github.io/facebook1/
Fixes #1738
=> room filter added

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Sample:-https://shubham3211.github.io/facebook-sample-1/schedule.html
Fixes #1787
=> date and time disappear

src/backend/templates/rooms.hbs
In room page, room heading will be displayed, after track filter applies.
Fixes #1794.
Deployment link: https://adityahirapara.github.io/eventSiteWebApp/rooms.html
=> show room heading while applying track filter(#1794)

src/backend/templates/schedule.hbs
Fixes: #1812 
- Adds direct link of rooms to the schedule page.
Deployment link to review - https://agbilotia1998.github.io/fossasiaRoomDirect/schedule.html#Balboa
=> Adds direct link of rooms to schedule page

src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
sample :- https://shubham3211.github.io/-facebook-new/index.html
Fixes #1806
=> track name visible

src/backend/_scss/application.scss, src/backend/assets/js/session.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Resolves #1807
Preparation for #1800
This is a code refactor, which should have no affect on the UI.
It moves the styling of the starred/bookmarked sessions into CSS. The Javascript now just toggles a class on and off.
1. I used the class `.starred` for bookmarks which could get confused with `#starred` for the filter button.
I would be happy to use a different name for the class, if you like. (`.bookmarked` perhaps?)
2. ~I have only tested on the "schedule" page. According to the code, the starring feature happens on other pages too. I changed that code too but didn't test those pages!~
3. If you like I could try to deduplicate some of the repeated code. Is there a global JS file where we can store reusable functions?
Or should I start a namespaced global, perhaps `window.OpenEvent` so …
=> Refactor session bookmarks (use a CSS class)

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs
Fixes #1251.
Deployment link: https://adityahirapara.github.io/eventSiteWebApp/index.html
=> add full screen pop-out option of calendar view

src/backend/templates/schedule.hbs
Fixes #1820.
Deployment link: https://adityahirapara.github.io/eventSiteWebAppTwo/index.html
=> remove unnecessary rooms after applying filter in calendar view

src/backend/_scss/application.scss
Added margin for the pop-box.
Fixes #1823
=> Added margin for pop-box

.travis.yml, docs/INSTALLATION_LOCAL.md, package.json
Added a file watcher for the changes and restart the server.
Fixes #1829
=> Added file watcher in dev dependencies

src/backend/templates/schedule.hbs
Improves png download of schedule.
- Adds flag to check if any of date is selected or not, if not then it downloads the complete schedule. 
Fixes #1833 
Deployment Link: https://agbilotia1998.github.io/fossasia/schedule.html
=> Fixes png download of schedule in list view

.codacy.yml
Improves project grade quality.
- Adds all assets to codacy exclude path 
Fixes #1837
=> Adds all assets to codacy exclude path

package.json
Fixes build issue on heroku
Deployment link: https://openeveweb.herokuapp.com/
Fixes #1840
=> Fixes heroku build issue

src/backend/generator.js
Fixes logo division of session page when logo_url is null
Deployment Link: https://agbilotia1998.github.io/OpenTechSummit/sessions/session_4693.html
Fixes #1841
=> Fixes logo division when logo_url is null in single session style

src/selenium/basePage.js, src/selenium/roomPage.js, src/selenium/schedulePage.js, src/selenium/trackPage.js, test/serverTest.js
Adds selenium tests for direct link of rooms and tracks.
Fixes #1835
=> Fixes #1835 Adds selenium tests for direct link of room and track filter

src/backend/templates/schedule.hbs
Changes URL dynamically on click of filters on schedule page
Test Link: https://agbilotia1998.github.io/ScheduleFilters/
Fixes #1850
=> Changes URL dynamically on click of filters

src/backend/templates/tracks.hbs
Adds direct link of room filter to the tracks page.
Test Link: https://agbilotia1998.github.io/FossasiaTrackDirect/tracks.html#Balboa
Fixes #1838
=> Adds room filter direct link to tracks page

src/backend/fold_v2.js
Fixes ticket url in v2 API format.
- Corrects the ticket url field according to v2 format.
Fixes #1853
=> Corrects API format v2 for ticket

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Fixes position of helper text.
Fixes #1832
=> Fixes position of helper text when no result is found

test/serverTest.js
Fixes travis test for broken link count.
Fixes #1863
=> Fixes broken link count in travis

src/backend/templates/partials/social.hbs
=> Fixes class of linkedIn share division

src/backend/_scss/application.scss, src/backend/fold_v2.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
Adds youtube video player.
Fixes #1810 
Preview Link: https://agbilotia1998.github.io/GoogleIO-17/
@geekyd @mariobehling FOSSASIA Summit 17 sample has been updated with the video URLs
Link to the PR: https://github.com/fossasia/open-event/pull/270
=> Adds video streaming iframe

.travis.yml, test/generatorAndSchedule.js, test/roomsAndSpeakers.js, test/serverTest.js, test/sessionAndEvent.js, test/tracks.js
=> [Fixes #1601] - Parallelizes travis build

src/backend/generator.js
=> Fixes app crash when uploaded zip is void

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
Fixes #1872 
Preview Link: https://agbilotia1998.github.io/GoogleIO-17/rooms.html
=> Fixes mobile view of video iframe

.travis.yml
Adds environment variable for google cloud deployment.
Follow up on #1601
=> Adds environment variable for google cloud deployment

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Makes track-title clickable on the expansion of session and links to the filter of that track.
Fixes #1886 
Preview Link: https://agbilotia1998.github.io/GoogleIO-17
=> Makes track-title clickable

src/backend/_scss/application.scss, src/backend/generator.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
Adds pdf viewer for the slides
Fixes #1883 
Screenshot:
Link to review: https://agbilotia1998.github.io/Moz-pdf/
=> Adds pdf viewer for the slides

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Makes room title clickable and enables filtering on click.
Fixes #1910 
Test Link: https://agbilotia1998.github.io/FossasiaRooms
=> Makes room-name clickable in expandable session style

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Extends div for which direct link is used.
Screenshot:
Fixes #1755 
Test Link: https://opev-gen.herokuapp.com/
=> Direct link expands the division in expandable session style

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss
Fixes #1902 
Sample:-https://shubham3211.github.io/fb-scroll/
=> scrollbar radius and color changed

src/backend/_scss/_base/_config.scss, src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
Fixes: #1875 
Follow up on : #1873
=> Allows fullscreen view and improves UI of video button

test/sessionAndEvent.js
Fixes Travis build for event page.
- Changed broken link count to 2 (https://www.imda.gov.sg/industry-development/spaces/pixel-labs and
http://www.xltech.io)
Fixes #1925
=> Fixes travis build x.5

src/backend/assets/js/main.js, src/backend/fold_v1.js, src/backend/fold_v2.js, src/backend/gulpfile.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
Adds video stream feature for sessions in v1 web apps and also incorporates slides data on rooms page.
Fixes: #1892 #1914 
Preview Link: https://agbilotia1998.github.io/Fossasia2018
=> Adds video stream support to v1 web apps

src/backend/_scss/application.scss, src/backend/fold_v1.js, src/backend/fold_v2.js, src/backend/generator.js, src/backend/templates/CoC.hbs, src/backend/templates/partials/footer.hbs
Adds code of conduct to the generated event website.
- Adds Code of conduct in the footer
Fixes #1921 
Preview Link: https://agbilotia1998.github.io/OWA-COC/
=> Adds code of conduct to the web app

src/backend/_scss/application.scss, src/backend/assets/js/main.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
It aligns audio, video, and slides 
Fixes #1927
Screenshot:
Preview Link: https://agbilotia1998.github.io/Eval-1/
=> Aligns audio, video and slides icon and their iframes

src/app.js, src/backend/dist.js, src/backend/generator.js, src/www/js/form.js
Enables multiple file upload at the same time in multiple sessions.
- Modified file name such that it does not depend on socket connection id.
Fixes #1923 
Test Link: https://open-event-webapp.herokuapp.com/
=> Fixes multiple zip file upload structure

src/backend/_scss/application.scss, src/backend/templates/schedule.hbs
Aligns filter list with the calendar in the calendar view.
Screenshot:
Preview link:
https://agbilotia1998.github.io/OWA/schedule.html
Fixes #1944
=> Fixes filter list view in calendar mode

.travis.yml, npm-shrinkwrap.json, package.json, src/.eslintrc, src/app.js, src/backend/generator.js, src/www/js/form.js
Implements task queue in the project, which enables multiple web app generation without the loss of request from the user.
- Implemented queue backed by Redis server.
Fixes #1856 
Link to test the changes: https://openeveweb.herokuapp.com/
API endpoints for testing:
- v1:
`https://eventyay.com/api/v1/events/200`
- v2:
`https://raw.githubusercontent.com/fossasia/open-event/master/sample/MozillaAllHands17`
-PS: Heroku Redis server addon needs to be enabled before merging this PR.
=> Implements task queue in the project

src/backend/generator.js, test/generatorAndSchedule.js, test/roomsAndSpeakers.js, test/serverTest.js, test/sessionAndEvent.js, test/tracks.js
Fixes overview site samples by adding specifying the theme field in the data object.
Fixes #1947
=> Adds theme field to data object in selenium tests

src/backend/_scss/application.scss
Aligns code-of-conduct data
Screenshot:
Preview Link:
https://agbilotia1998.github.io/OWA-COC/CoC.html
Fixes #1953
=> Aligns code of conduct data

src/backend/_scss/application.scss
Sample:-https://shubham3211.github.io/google-video/index.html
https://secure-brook-31694.herokuapp.com/
Fixes #1952
=> video width adjusted

src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Fixes #1945 
Sample :- https://shubham3211.github.io/google-nothing-found/index.html
=> no result found shown

docs/INSTALLATION_HEROKU.md, docs/INSTALLATION_LOCAL.md
Adds documentation for installation and running of Redis server.
Fixes #1959
=> Adds documentation for enabling Redis

src/backend/templates/session.hbs
Removes multiple horizontal rules from single session style pages
Screenshot:
Test link: https://opev-gen.herokuapp.com/
Fixes #1957
=> Removes multiple horizontal rules from single session style pages

src/backend/_scss/application.scss, src/backend/templates/session.hbs, src/selenium/sessionPage.js
Adds dark-theme to single session style pages.
Preview link: https://agbilotia1998.github.io/OWA-dark-theme/sessions/session_1268.html
Fixes #1963
=> Adds dark-theme to single session style pages

src/backend/_scss/application.scss, src/backend/assets/js/main.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Removes blinking of video icon and fixes the position of all icons.
Screenshot:
Preview link: https://agbilotia1998.github.io/IO-videos/schedule.html
Fixes #1969
=> Removes blinking of video icon and fixes position of all icons

README.md
Adds API specifications for generate route.
Fixes #1971
=> Adds API specifications

src/app.js
Adds request waiting number in logs.
Test server: https://openeveweb.herokuapp.com/
Fixes #1980
=> Adds request waiting number in logs

src/backend/overviewSite/index.html
Makes the caption clickable along with the event image similar to eventyay.
Preview link: https://agbilotia1998.github.io/overview-site/
Fixes #1985
=> Makes the caption clickable

src/backend/generator.js, src/backend/templates/session.hbs
Integrates calendar API with single session style apps.
Server Link: https://openeveweb.herokuapp.com/
Fixes #1983
=> Integrates calendar API with single session style apps

src/backend/assets/js/main.js, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/tracks.hbs
Fixes #2005 
Sample:- https://shubham3211.github.io/filter-remove/
=> remove nothing found from different template

src/backend/_scss/application.scss, src/backend/assets/dependencies/tweets.js
Fixes No tweets error and word break in the twitter feed.
Screenshot: 
Preview link: https://agbilotia1998.github.io/OSCON17/
Fixes #2018 
PS: gh-pages may take some time to build.
=> Fixes No tweets error and word break in twitter feed

src/backend/generator.js
Gets socket status and logger in sync while compiling the HTML pages from the templates.
Screenshots:
Server Link: https://opev-gen.herokuapp.com/
Fixes #2012
=> Gets socket status and logger in sync

src/backend/_scss/application.scss
Fixes #2014 
Screenshot:- 
Sample :- https://shubham3211.github.io/filter-remove/
=> social icons now visible

src/backend/_scss/application.scss, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/tracks.hbs
Fixes the position of Add to calendar button.
Server link: https://openeveweb.herokuapp.com/
API endpoint:  https://raw.githubusercontent.com/fossasia/open-event/master/sample/FOSSASIASummit2016
Screenshot: 
Fixes #2038
=> Fixes the position of Add to calendar button

src/backend/templates/schedule.hbs
Implements the pdf download of the complete calendar.
Server link: https://openeveweb.herokuapp.com/
API endpoint: https://raw.githubusercontent.com/fossasia/open-event/master/sample/GoogleIO17
Fixes #1978
=> Implements the PNG download of complete calendar

src/selenium/basePage.js, src/selenium/roomPage.js, src/selenium/schedulePage.js, src/selenium/trackPage.js, test/generatorAndSchedule.js, test/roomsAndSpeakers.js, test/tracks.js
Adds selenium tests for the dynamic link of filters.
Fixes #2036
=> Adds selenium tests for dynamic link of filters

src/backend/_scss/application.scss, src/backend/dist.js, src/backend/fold_v1.js, src/backend/fold_v2.js, src/backend/generator.js, src/backend/templates/schedule.hbs
Adds attendees section similar to sched.org
Server link: https://open-event-webapp.herokuapp.com/
Zip file: https://drive.google.com/file/d/1bB4lZvv-CgmY5Ixx03v2x-alSz9A1Tyf/view?usp=sharing
Fixes #2048
=> [Fixes#2048]Adds attendees section to schedule page [PART-1]

src/backend/dist.js, src/backend/fold_v2.js, src/backend/generator.js, test/serverTest.js
Enables web app generation from eventyay v2 platform.
Server link: https://webapp-generator.herokuapp.com/
API endpoint: https://open-event-api-dev.herokuapp.com/v1/events/767
Fixes #2046
PS: I've removed the FB17 sample from tests, as the sample has some problem and this PR was a priority. I will fix the sample and add it back again to the test suite.
=> Enables web app generation from eventyay v2 platform

test/generatorAndSchedule.js, test/roomsAndSpeakers.js, test/tracks.js
Fixes Travis builds after merging of PR.
Fixes #2071
=> Fixes travis build

src/selenium/basePage.js, test/generatorAndSchedule.js, test/roomsAndSpeakers.js, test/sessionAndEvent.js, test/tracks.js
=> Adds selenium tests for checking the dark theme customizations

.travis.yml, src/selenium/cocPage.js, test/sessionEventAndCoC.js
=> Adds selenium tests for the Code of Conduct page

src/backend/dist.js
Fixes download of large size background image.
Screenshot:
Test Link: https://open-event-webapp.herokuapp.com/
Fixes #2082
=> Fixes download of large size background image

src/backend/_scss/application.scss
Fixes positioning of ticket button
Screenshot:
Fixes #2087
=> Fixes positioning of ticket button

src/backend/_scss/application.scss
- Made it look the the https://2018.fossasia.org/
-
-
Fixes https://github.com/fossasia/open-event-webapp/issues/2092
=> Space between text and image decreased

.travis.yml, package.json
Fixes Heroku build.
- Specifies npm version for deployment.
Fixes #2118
=> Fixes Heroku build

.travis.yml
It fixes the failing of travis
- This will fix the travis failing issue.
Fixes https://github.com/fossasia/open-event-wsgen/issues/2128
=> fixes failing of travis

src/backend/_scss/application.scss
Fixed the padding issue for social profile links in the footer menu
Fixes #2159 
[Test link](https://dishebh.github.io/open-event-wsgen/FOSSASIASummit/index.html)
=> Fixed the padding issue

src/backend/templates/schedule.hbs
Made the sessions page same as the tracks page.
Fixes #2137
=> Fixed the sessions page

README.md
=> Update The Readme Badges

src/backend/assets/js/main.js, src/backend/generator.js, src/backend/templates/schedule.hbs, test/serverTest.js, test/sessionEventAndCoC.js
Schedule Calendar switcher broken in #2121 
Track layout and direct link broken in #2157 
For #2128
=> fix: Many recent PRs which broke tests and site

.gitignore, src/backend/dist.js, src/backend/templates/event.hbs, src/backend/templates/partials/footer.hbs, src/backend/templates/partials/navbar.hbs, src/backend/templates/rooms.hbs, src/backend/templates/schedule.hbs, src/backend/templates/session.hbs, src/backend/templates/speakers.hbs, src/backend/templates/tracks.hbs
Also add option to skip downloads to develop faster
=> fix: HTML syntax errors and XSS vulnerabilities

.gitignore, npm-shrinkwrap.json, package.json, src/backend/fold_v2.js
=> feat: Download photos concurrently

src/backend/templates/partials/footer.hbs
=> fix: address beginning with comma

.gitignore, src/app.js, src/backend/dist.js
=> chore: Synchronize socket PID retrieval

.travis.yml
Reverts fossasia/open-event-wsgen#2211
=> Revert "chore: Use local chrome webdriver"

src/www/index.html
- Use autocomplete attribute
Fixes #2081
=> fix: Enable url input field to store the past input data

src/backend/fold_v2.js
Deserializer while deserializing event json appends null in the social-links which was not handled while working on each link object. 
- Use filter function to remove null elements from the array of social-links
Fixes #2389
=> fix: Remove null element from the list of social links
